In [3]:
import torch


a = torch.randn(5,15)
a
a.view(-1, 5, 3)

tensor([[[ 0.9163, -1.0319,  1.1541],
         [-0.8929, -0.7601, -0.5124],
         [ 0.8299,  0.9084,  1.1240],
         [-0.0319,  1.6515,  0.2132],
         [-1.5268, -0.6304,  0.2863]],

        [[ 1.3651,  0.7780,  0.1746],
         [ 0.4370,  0.1957,  0.3862],
         [ 1.6441, -0.3647, -0.5030],
         [ 1.0296,  0.7601, -0.1926],
         [ 0.4760,  0.9171,  1.2085]],

        [[-0.9355, -0.1565,  0.0814],
         [ 0.0493,  0.3285, -0.7979],
         [-0.7939,  0.3020,  1.9040],
         [ 1.0765, -0.5612,  0.9802],
         [ 0.6643,  1.2297,  0.9311]],

        [[ 0.9803, -0.0100,  0.4790],
         [ 0.5977, -0.0617, -1.5921],
         [ 0.3832, -0.5515, -0.1216],
         [-0.4067,  1.0117, -0.3642],
         [ 0.1635, -0.1003,  0.0280]],

        [[-0.3550,  0.5742, -0.2712],
         [-0.8868,  0.6334, -0.1765],
         [-1.3139,  2.0587, -0.9394],
         [ 0.0979,  0.2138, -0.6802],
         [ 0.1573, -0.6194,  1.2933]]])

In [6]:
torch.cross(a.view(-1, 5, 3),a.view(-1, 5, 3), dim=2)

tensor([[[-2.8741e-08, -5.7919e-08, -1.7975e-08],
         [-1.4534e-09, -3.1904e-09,  1.5473e-08],
         [ 4.9062e-08,  2.3603e-08, -2.8895e-09],
         [-1.3438e-08,  7.0887e-11,  1.7731e-09],
         [-4.6302e-09,  3.1365e-09, -2.1455e-08]],

        [[-3.2152e-09,  1.7824e-09,  4.5334e-08],
         [ 3.0826e-10, -1.7691e-09,  3.0028e-09],
         [-3.8146e-10,  4.3011e-09, -3.9038e-09],
         [-6.0105e-09, -2.1000e-09,  2.2124e-08],
         [ 3.5287e-08, -1.4479e-08, -1.4221e-08]],

        [[ 4.4438e-10,  2.7452e-09,  4.1075e-11],
         [-7.1141e-09, -2.4409e-10,  1.2820e-10],
         [-1.7281e-09,  1.8695e-09, -2.8259e-10],
         [-1.6604e-08,  4.6185e-08,  7.2750e-09],
         [-3.5811e-08,  1.7603e-08,  1.9976e-08]],

        [[-2.0785e-10, -1.3619e-08, -2.3345e-10],
         [ 2.3185e-09,  2.2792e-08, -4.9987e-10],
         [ 1.7938e-09,  4.2202e-10,  2.7035e-09],
         [ 7.9555e-09,  2.1907e-09,  6.3486e-09],
         [ 3.8206e-11,  9.1859e-11, -7.1301e

In [13]:
x = torch.rand(10, 3)
y = torch.rand(10, 4)

res = torch.bmm(x.unsqueeze(2), y.unsqueeze(1))
res.size()

torch.Size([10, 3, 4])

In [20]:
a = torch.arange(10, dtype= torch.float) - 5
b = a.reshape((2, 5))
torch.norm(a)

torch.norm(b, dim=0)

tensor([5.0000, 4.1231, 3.6056, 3.6056, 4.1231])

In [22]:
import torch.nn as nn
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
print(input)
print(output)

tensor([[-1.5286,  0.6844,  1.3201],
        [-0.9700,  0.8762, -1.6023]])
tensor([[0.0365, 0.3336, 0.6299],
        [0.1271, 0.8053, 0.0675]])


In [25]:
a = torch.arange(12, dtype= torch.float)
a = a.reshape((1, 2, 2, 3))

b = torch.arange(2, dtype= torch.float)
b = b.reshape((1, 2))

print(a, b)

b = b.unsqueeze(2).unsqueeze(3)
b = b.expand(1, 2, 2, 3)

tensor([[[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],

         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]]) tensor([[0., 1.]])


In [26]:
print(b)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[1., 1., 1.],
          [1., 1., 1.]]]])


In [27]:
torch.mul(a, b)

tensor([[[[ 0.,  0.,  0.],
          [ 0.,  0.,  0.]],

         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]])

In [84]:
a = torch.arange(18, dtype= torch.float)
a = a.reshape((2, 3, 3))
a = torch.rand(2,3,3)
print(a)
b = torch.arange(9, dtype= torch.float)
b = b.reshape((3, 3))
c = torch.matmul(b, a)
print(c.size())
d = torch.matmul(c, b.t())
print(d.size())

tensor([[[0.3364, 0.1947, 0.2533],
         [0.2657, 0.2613, 0.8381],
         [0.1944, 0.9009, 0.9864]],

        [[0.2029, 0.5477, 0.7197],
         [0.2556, 0.1864, 0.8808],
         [0.4702, 0.1975, 0.5250]]])
torch.Size([2, 3, 3])
torch.Size([2, 3, 3])


In [58]:
e = torch.eye(3)
print(e)
f = torch.mul(d, e)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [56]:
g,_ = f.max(-1)
print(g.size())

torch.Size([2, 3])


In [83]:
h = torch.arange(10, dtype = torch.float)
h = h.reshape((2, 5))

# i = torch.arange(15, dtype = torch.float).reshape((3, 5))
i = torch.randn(3,5)

loss_f = nn.KLDivLoss(size_average=False, reduce=False)# True  
softmax = nn.Softmax(dim=1)

for j in h:
    j = j.unsqueeze(0).expand(3, -1)
    a_ = softmax(i)
    t_ = softmax(j)
    print('a',a_)
    print('t',t_)
    print(loss_f(a_, t_))
    print((0 - torch.mean(loss_f(a_, t_), 1)).size())
    

a tensor([[0.2303, 0.4264, 0.1187, 0.1040, 0.1206],
        [0.3506, 0.4768, 0.1103, 0.0350, 0.0273],
        [0.1079, 0.6291, 0.1942, 0.0194, 0.0494]])
t tensor([[0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364]])
tensor([[-0.0546, -0.1229, -0.2214, -0.3643, -0.3644],
        [-0.0560, -0.1245, -0.2207, -0.3481, -0.3050],
        [-0.0532, -0.1293, -0.2279, -0.3445, -0.3190]])
torch.Size([3])
a tensor([[0.2303, 0.4264, 0.1187, 0.1040, 0.1206],
        [0.3506, 0.4768, 0.1103, 0.0350, 0.0273],
        [0.1079, 0.6291, 0.1942, 0.0194, 0.0494]])
t tensor([[0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364],
        [0.0117, 0.0317, 0.0861, 0.2341, 0.6364]])
tensor([[-0.0546, -0.1229, -0.2214, -0.3643, -0.3644],
        [-0.0560, -0.1245, -0.2207, -0.3481, -0.3050],
        [-0.0532, -0.1293, -0.2279, -0.3445, -0.3190]])
torch.Size([3])
